#!/bin/bash

if grep -q Microsoft /proc/version; then
    iswsl = "t"
else
    iswsl = "f"
fi


read -p "Set git configs? y/n: " gitConf

if [ "$gitConf" = "y" ]; then
    read -p "What's your name?: " name
    read -p "What's your mail?: " mail
    git config --global user.name "$name"
    git config --global user.email "$mail"
fi

read -p "Add ssh keys?: " sshAdd

more_ssh_loop() {
    while true
    do
	read -r -p 'Add more ssh key(s)? ' choice
	case "$choice" in
	    n|N) break;;
	    y|Y)
		read -p "What should the file be called?: " name
		ssh-keygen -t rsa -b 4096 -q -f "$HOME/.ssh/$name" -N "" -C "$mail"
		;;
	    *) echo 'Response not valid';;
	esac
    done
}

if [ "$sshAdd" = "y" ]; then
    if [ ! -d "$HOME/.ssh" ]; then
	mkdir $HOME/.ssh
    fi

    if [ "$gitConf" = "y" ]; then
	read -p "What should the file be called?: " name
	ssh-keygen -t rsa -b 4096 -q -f "$HOME/.ssh/$name" -N "" -C "$mail"
    else
	read -p "What should the file be called?: " name
	read -p "What's your mail?: " mail
	ssh-keygen -t rsa -b 4096 -q -f "$HOME/.ssh/$name" -N "" -C "$mail"
    fi
    more_ssh_loop
fi

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

yadm remote set-url origin "git@github.com:YousofMersal/Dotfiles.git"

sudo apt update 

sudo apt dist-upgrade -y

sudo apt install zsh neovim python3-pip build-essential gdb ripgrep -y

wget -P ~ https://git.io/.gdbinit

git clone https://github.com/gpakosz/.tmux.git

ln -s -f ~/.tmux/.tmux.conf 

cp ~/.tmux/.tmux.conf.local .

if [ "$iswsl" = "t" ]; then
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
else
    curl https://sh.rustup.rs -sSf | sh -s -- -y
fi

cargo install exa

sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

yadm pull origin master -f

pip3 install pynvim

pip3 install pygments

nvim --headless +'PlugInstall --sync' +'PlugUpdate' +qa

curl -s "https://get.sdkman.io" | bash

source "$HOME/.sdkman/bin/sdkman-init.sh"

sdk install java 14.0.2.fx-librca

curl -L https://git.io/n-install | bash


chsh -s $(which zsh)
